application:
  max-allowed-books: 2

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libdb
    username: myuser
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update